### ISSUE TITLE
cvtColor error

### ISSUE THREAD

**Issue by akshat9425** [openfoodfacts/off-nutrition-table-extractor#20]
please tell me how to resolve issue

cv2.error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/color.cpp:181: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

**Comment by VeenaPulicharla** [comment]
I checked that source image array, its not empty, getting error at this line24, 'img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) while image enhancement.
